# Generated by Django 2.1.1 on 2018-09-29 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Assignment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='textentry',
            old_name='user_id',
            new_name='user',
        ),
    ]
