# Generated by Django 2.0.3 on 2018-09-29 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assignment', '0003_auto_20180929_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textentry',
            name='data',
            field=models.TextField(max_length=255),
        ),
    ]
