# Generated by Django 2.0.3 on 2018-09-29 19:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assignment', '0005_auto_20180929_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textentry',
            name='data',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 255', regex='^.{255}$')]),
        ),
    ]
