# Generated by Django 2.0.3 on 2018-09-29 19:05

import Assignment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assignment', '0006_auto_20180929_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textentry',
            name='data',
            field=models.CharField(max_length=255, validators=[Assignment.models.validate_length]),
        ),
    ]
