# Generated by Django 2.0.3 on 2018-09-29 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Assignment', '0008_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='activation_key',
        ),
    ]
